config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#show'

  devise_for :users
  resources :messages, only: %i(index show create destroy)
  resources :users, except: %i(show destroy edit)
  get 'users/edit', to: 'users#edit'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :text, :user, presence: true
  belongs_to :user

  def unread?(user)
    id > user.read_to
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable

  IMAGE_STYLES = { normal: '64x64#' }.freeze
  IMAGE_TYPE = %w(image/jpeg image/png image/gif).map(&:freeze)
  has_attached_file :avatar,
                    styles: IMAGE_STYLES,
                    default_style: :normal,
                    default_url: 'noavatar.png'
  validates_attachment_content_type :avatar, content_type: IMAGE_TYPE
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action:configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :full_name << :email << :avatar
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  protect_from_forgery except: :index
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  after_action :update_read_to, only: [:index]

  def index
    @messages = if params[:max_id].present?
                  Message.where('id <= ?', params[:max_id]).last(25)
                else
                  Message.last(25)
                end
    render
  end

  def show
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      render :show, status: :created, location: @message
      MessageBroadcastJob.perform_later(method: 'create', message: @message)
    else
      render json: @message.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @message.destroy
    MessageBroadcastJob.perform_later(method: 'destroy', id: @message.id)
    head :no_content
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:text, :user_id)
  end

  def update_read_to
    return if @messages.empty? || current_user.read_to >= @messages.last.id
    current_user.update(read_to: @messages.last.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :full_name, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    ENV['APP_NAME'] || Rails.application.class.parent_name
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def format(source)
    result = Rails.application.config.pipeline.call(source)[:output]
    result.gsub(/(\r\n|\r|\n)/, '<br />')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= app_name %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

  <% if user_signed_in?  %>
    <nav class='global_nav'>
      <ul>
        <li class='brand'>
          <%= link_to app_name, root_path %>
        </li>
        <li class='spacer'></li>
        <li>
          <%= link_to users_path do %>
            <i class='fa fa-users'></i> Users
          <% end %>
        </li>

        <li>
          <%= link_to users_edit_path do %>
            <i class='fa fa-pencil-square-o'></i> Edit profile
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: 'delete' do %>
            <i class='fa fa-sign-out'></i> Logout
          <% end %>
        </li>
      </ul>
    </nav>
  <% end %>

  <% if flash[:error] %>
    <%= content_tag(:div, 'This is error', class: "flash_error") do %>
      <i class='fa fa-exclamation-circle'></i> <%= flash[:error] %>
    <% end %>
  <% end %>

  <% if flash[:alert] %>
    <%= content_tag(:div, 'This is error', class: "flash_alert") do %>
      <i class='fa fa-bell'></i>  <%= flash[:alert] %>
    <% end %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<li class='message <%= "unread" if local_assigns[:broadcast] || message.unread?(current_user) %>' data-message-id='<%= message.id %>'>
  <%= image_tag message.user.avatar.url, class: 'avatar' %>
  <p class='delete_link'>
    <%= link_to message_path(message), method: :delete, remote: true do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </p>
  <p class='created_at'><%= message.created_at.strftime('%Y-%m-%d %H:%M') %></p>
  <p class='full_name_and_name'>
    <span class='full_name'><%= message.user.full_name%></span>
    -
    <span class='name'><%= message.user.name%></span>
  </p>
  <p class='text'><%== format(message.text) %></p>
</li>

app/views/messages/index.html.erb
<ul id='messages' class='timeline_area'></ul>

<%= form_tag(messages_path(format: 'json'), method: :post, remote: true, id: 'message_post_form', class: 'message_post_form') do |f| %>
  <%= hidden_field_tag 'message[user_id]', current_user.id %>
  <%= text_area :message, :text, placeholder: 'Press Ctrl + Enter to post it', id: 'message_area' %>
  <%= submit_tag 'Post' %>
<% end  %>

<%= javascript_include_tag messages_path(format: 'js') %>

app/views/messages/index.js.erb
<% if @messages.empty? %>
  retrieve = function() {}
<% else %>
  retrieve = function() {
    window.on_loading = true
    $.getScript("<%= messages_path(max_id: @messages.first.id - 1, format: 'js') %>")
      .always(function() {
        window.on_loading = false
      });
  };

  (function () {
    var offset = $('#messages').scrollBottom();
    $('#messages').prepend('<%= j(render @messages) %>');
    $('#messages').scrollBottom(offset);
  })();
<% end %>

app/views/rooms/show.html.erb
<ul id='messages' class='timeline_area'></ul>

<%= form_tag(messages_path(format: 'json'), method: :post, remote: true, id: 'message_post_form', class: 'message_post_form') do |f| %>
  <%= hidden_field_tag 'message[user_id]', current_user.id %>
  <%= text_area :message, :text, placeholder: 'Press Ctrl + Enter to post it', id: 'message_area' %>
  <%= submit_tag 'Post' %>
<% end  %>

<%= javascript_include_tag messages_path(format: 'js') %>

app/views/users/_user.html.erb
<tr>
  <td><%= image_tag user.avatar.url %></td>
  <td><%= user.name %></td>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
</tr>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class='user-container'>
  <h2>New User</h2>

  <%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :name%><br />
      <%= f.text_field :name, readonly: true%>
    </div>
    <div class="field">
      <%= f.label :full_name %><br />
      <%= f.text_field :full_name, placeholder: 'Your full name (e.g. Franc Dabell)', autofocus: true %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field profile_image_field">
      <%= f.label :avatar, 'Profile image' %><br />
      <%= image_tag current_user.avatar.url %>
      <%= f.file_field 'avatar' %>
    </div>

    <div class="actions">
      <%= f.submit "Update" %>
    </div>
  <% end %>

  <%= link_to "Cancel", root_path %>
</div>

app/views/users/index.html.erb
<div class='user-container'>
  <h2>Users</h2>
</div>

<table class='user-table'>
  <thead>
    <tr>
      <th></th>
      <th>ID</th>
      <th>Full name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

<div class='user-container'>
  <%= link_to new_user_path do %>
    <i class='fa fa-user-plus'></i> Add user
  <% end %>
</div>

app/views/users/new.html.erb
<div class='user-container'>
  <h2>New User</h2>

  <%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :name%><br />
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="field">
      <%= f.label :full_name %><br />
      <%= f.text_field :full_name, placeholder: 'Your full name (e.g. Franc Dabell)' %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email %>
    </div>

    <div class="actions">
      <%= f.submit "Add user" %>
    </div>
  <% end %>

  <%= link_to "Cancel", root_path %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>